import {
  GOOGLE_CLIENT_ID_ANDROID,
  GOOGLE_CLIENT_ID_IOS,
  FACEBOOK_APP_ID,
  APPLE_CLIENT_ID,
  APPLE_REDIRECT_URI,
  BASE_URL,
} from '@env'

export const env = {
  GOOGLE_CLIENT_ID_ANDROID: GOOGLE_CLIENT_ID_ANDROID as string,
  GOOGLE_CLIENT_ID_IOS: GOOGLE_CLIENT_ID_IOS as string,
  FACEBOOK_APP_ID: FACEBOOK_APP_ID as string,
  APPLE_CLIENT_ID: APPLE_CLIENT_ID as string,
  APPLE_REDIRECT_URI: APPLE_REDIRECT_URI as string,
  BASE_URL: BASE_URL as string,
}
